### ISSUE TITLE
Implementation wrong in some lines of code 

### ISSUE THREAD

**Issue by 0xKarl98** [sky-ecosystem/optimism-dai-bridge#84]
For example ,  in contracts/L2/L2DAITokenBridge.sol 

there is 
```
_initiateWithdrawal(msg.sender, msg.sender, _amount, _l1Gas, _data); 
```
which should be 
```
_initiateWithdrawal(msg.sender, msg.value ,  _amount, _l1Gas, _data);  
```

Since the second argument is amount , it should be msg.value

**Comment by krzkaczor** [comment]
Second argument is `to`. 

```
 function _initiateWithdrawal(
    address _from,
    address _to,
    uint256 _amount,
```

Also, such a mistake would be trivially caught by a solidity compiler (not to mention tests).
